services:
  app:
    image: jasonly027/io_blair_backend
    build:
      dockerfile: ./docker/app.Dockerfile
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      - SERVER_PORT=${SERVER_PORT:-8080}
  tests:
    build:
      dockerfile: ./docker/test.Dockerfile
