services:
  app:
    image: jasonly027/io_blair_backend
    environment:
      - SERVER_PORT=8080
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ioblair.rule=Host(`ioblair-server.uk`)"
        - "traefik.http.services.ioblair.loadbalancer.server.port=8080"
        - "traefik.http.routers.ioblair.entrypoints=websecure"
        - "traefik.http.routers.ioblair.tls.certresolver=myresolver"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
