/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: A Random Acorn ฅ՞•ﻌ•՞ฅ (https://sketchfab.com/I_think_im_a_toaster_now_0o0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/waffle-cat-sandwich-3-52289763f9c146698a38007bc0672cd9
Title: Waffle Cat Sandwich :3
*/

import { useGLTF } from "@react-three/drei";

export default function CatWaffle() {
  const { nodes, materials } = useGLTF("/models/CatWaffle/scene.gltf");
  return (
    <group dispose={null}>
      <group rotation={[-3.14, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.color_14541540}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.color_14860437}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.color_15277357}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.color_16089887}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.color_16768282}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.color_16770912}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.color_2829873}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.color_4634441}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.color_6306067}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/CatWaffle/scene.gltf");
